### ISSUE TITLE
To add jupyter notebooks of some algorithms

### ISSUE THREAD

**Issue by Anjali001** [LATAM-Data-Science-Study-Group/Data-Science-Notebooks#11]
Hey. I wish to add well explained jupyter notebooks for k means clustering , decision trees and linear regression. 
Please add hacktober fest label to it.

**Comment by JoelBuenrostro** [comment]
Label added

**Comment by Anjali001** [comment]
Thanks. 
Also, I just noticed that someone has already done K Means, so I'll leave that and do the rest two. I hope that's fine.

**Comment by JoelBuenrostro** [comment]
Ok, also no problem if you are using K-means but with a different datasets or focus
