### ISSUE TITLE
Data Science Foundations

### ISSUE THREAD

**Issue by Dhruv-VINT** [LATAM-Data-Science-Study-Group/Data-Science-Notebooks#3]
I would like to add python notebooks which are essential for building the core for Data Science/Machine Learning, The work I'm willing to do will include tutorials on libraries such as Numpy, Pandas, Seaborn & also a few EDA notebooks to provide a hands on implementation of such libraries. 

Me gustaría agregar cuadernos de Python que son esenciales para construir el núcleo de ciencia de datos y aprendizaje automático. 

@JoelBuenrostro  I would love to work on this project for a greater cause !

**Comment by JoelBuenrostro** [comment]
Great, we could translate them into Spanish later to share with the rest of the community. Thank you

**Comment by Dhruv-VINT** [comment]
Awesome ! So shall I proceed with coding & contributing part now?
